# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: slinky 0.8.2 ruby lib
# stub: ext/transitive_closure/extconf.rb

Gem::Specification.new do |s|
  s.name = "slinky"
  s.version = "0.8.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Micah Wylde"]
  s.date = "2014-11-07"
  s.description = "A static file server for rich web apps that automatically compiles SASS, HAML, CoffeeScript and more"
  s.email = "micah@micahw.com"
  s.executables = ["slinky"]
  s.extensions = ["ext/transitive_closure/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/slinky",
    "ext/transitive_closure/extconf.rb",
    "ext/transitive_closure/transitive_closure.c",
    "lib/slinky.rb",
    "lib/slinky/builder.rb",
    "lib/slinky/compiled_file.rb",
    "lib/slinky/compilers.rb",
    "lib/slinky/compilers/clojurescript-compiler.rb",
    "lib/slinky/compilers/coffee-compiler.rb",
    "lib/slinky/compilers/haml-compiler.rb",
    "lib/slinky/compilers/jsx-compiler.rb",
    "lib/slinky/compilers/less-compiler.rb",
    "lib/slinky/compilers/sass-compiler.rb",
    "lib/slinky/config_reader.rb",
    "lib/slinky/em-popen3.rb",
    "lib/slinky/errors.rb",
    "lib/slinky/graph.rb",
    "lib/slinky/listener.rb",
    "lib/slinky/live_reload.rb",
    "lib/slinky/manifest.rb",
    "lib/slinky/proxy_server.rb",
    "lib/slinky/pure_transitive_closure.rb",
    "lib/slinky/runner.rb",
    "lib/slinky/server.rb",
    "lib/slinky/templates/error.css",
    "lib/slinky/templates/error.haml",
    "lib/slinky/templates/error.js",
    "lib/slinky/templates/inject.css",
    "slinky.gemspec",
    "spec/compilers_spec.rb",
    "spec/manifest_spec.rb",
    "spec/slinky_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://mwylde.github.com/slinky/"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Static file server for javascript apps"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<multi_json>, ["~> 1.9.2"])
      s.add_runtime_dependency(%q<eventmachine>, ["~> 1.0"])
      s.add_runtime_dependency(%q<eventmachine_httpserver>, ["~> 0.2"])
      s.add_runtime_dependency(%q<em-websocket>, ["~> 0.3"])
      s.add_runtime_dependency(%q<em-proxy>, ["~> 0.1"])
      s.add_runtime_dependency(%q<rainbow>, ["~> 1.1"])
      s.add_runtime_dependency(%q<mime-types>, ["~> 1.16"])
      s.add_runtime_dependency(%q<uglifier>, ["~> 2.5"])
      s.add_runtime_dependency(%q<listen>, ["~> 2.4"])
      s.add_runtime_dependency(%q<haml>, ["~> 3.1"])
      s.add_runtime_dependency(%q<sass>, ["~> 3.3"])
      s.add_runtime_dependency(%q<coffee-script>, ["~> 2.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.10"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<bundler>, ["~> 1.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_development_dependency(%q<fakefs>, ["= 0.5.3"])
      s.add_development_dependency(%q<em-http-request>, ["~> 1.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<less>, [">= 2.2.0"])
      s.add_development_dependency(%q<therubyracer>, [">= 0"])
      s.add_development_dependency(%q<react-jsx>, ["~> 0.8.0"])
      s.add_development_dependency(%q<rake-compiler>, ["~> 0.9.3"])
    else
      s.add_dependency(%q<multi_json>, ["~> 1.9.2"])
      s.add_dependency(%q<eventmachine>, ["~> 1.0"])
      s.add_dependency(%q<eventmachine_httpserver>, ["~> 0.2"])
      s.add_dependency(%q<em-websocket>, ["~> 0.3"])
      s.add_dependency(%q<em-proxy>, ["~> 0.1"])
      s.add_dependency(%q<rainbow>, ["~> 1.1"])
      s.add_dependency(%q<mime-types>, ["~> 1.16"])
      s.add_dependency(%q<uglifier>, ["~> 2.5"])
      s.add_dependency(%q<listen>, ["~> 2.4"])
      s.add_dependency(%q<haml>, ["~> 3.1"])
      s.add_dependency(%q<sass>, ["~> 3.3"])
      s.add_dependency(%q<coffee-script>, ["~> 2.2"])
      s.add_dependency(%q<rspec>, ["~> 2.10"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<bundler>, ["~> 1.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_dependency(%q<fakefs>, ["= 0.5.3"])
      s.add_dependency(%q<em-http-request>, ["~> 1.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<less>, [">= 2.2.0"])
      s.add_dependency(%q<therubyracer>, [">= 0"])
      s.add_dependency(%q<react-jsx>, ["~> 0.8.0"])
      s.add_dependency(%q<rake-compiler>, ["~> 0.9.3"])
    end
  else
    s.add_dependency(%q<multi_json>, ["~> 1.9.2"])
    s.add_dependency(%q<eventmachine>, ["~> 1.0"])
    s.add_dependency(%q<eventmachine_httpserver>, ["~> 0.2"])
    s.add_dependency(%q<em-websocket>, ["~> 0.3"])
    s.add_dependency(%q<em-proxy>, ["~> 0.1"])
    s.add_dependency(%q<rainbow>, ["~> 1.1"])
    s.add_dependency(%q<mime-types>, ["~> 1.16"])
    s.add_dependency(%q<uglifier>, ["~> 2.5"])
    s.add_dependency(%q<listen>, ["~> 2.4"])
    s.add_dependency(%q<haml>, ["~> 3.1"])
    s.add_dependency(%q<sass>, ["~> 3.3"])
    s.add_dependency(%q<coffee-script>, ["~> 2.2"])
    s.add_dependency(%q<rspec>, ["~> 2.10"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<bundler>, ["~> 1.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
    s.add_dependency(%q<fakefs>, ["= 0.5.3"])
    s.add_dependency(%q<em-http-request>, ["~> 1.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<less>, [">= 2.2.0"])
    s.add_dependency(%q<therubyracer>, [">= 0"])
    s.add_dependency(%q<react-jsx>, ["~> 0.8.0"])
    s.add_dependency(%q<rake-compiler>, ["~> 0.9.3"])
  end
end

